scriptencoding utf-8
set nocompatible

" Plugins {{{
" Load packager only when you need it
function! PackagerInit() abort
  packadd vim-packager
  call packager#init()
  call packager#add('itchyny/lightline.vim')
  call packager#add('justinmk/vim-dirvish')
  call packager#add('ctrlpvim/ctrlp.vim')
  call packager#add('NLKNguyen/papercolor-theme')
  call packager#add('jnurmine/Zenburn')
  call packager#add('sickill/vim-monokai')
  call packager#add('Yggdroot/indentLine')
endfunction
" }}}
" Basic {{{
filetype plugin indent on
syntax on

set autoindent
set hidden
set modelines=1
set clipboard+=unnamed
set belloff=all
set ambiwidth=double
" }}}
" Searching {{{
set hlsearch
set ignorecase
set smartcase
set incsearch
" }}}
" Backups {{{
set nobackup
set nowritebackup
set noswapfile
set noundofile
" }}}
" Spaces & Tabs {{{
set shiftwidth=2
set tabstop=2
set expandtab
" }}}
" UI {{{
set number
set showcmd
set list lcs=eol:$,tab:>-
set laststatus=2
set cmdheight=2
"set statusline=%r%w%f%m%=[%{&fileformat}][%{&fileencoding}]%y[%3p%%][%3l:%-3c]
" }}}
" Colors {{{
set background=dark
colorscheme zenburn
" }}}
" Keymaps {{{
let mapleader = "\<Space>"
nnoremap Y y$
noremap <C-CR> o<Esc>
nnoremap <silent> <Leader>w :update<CR>
nnoremap <silent> <Leader>n :enew<CR>
nnoremap <silent> <Esc><Esc> :nohlsearch<CR>
nnoremap <Tab> <C-w><C-w>
nnoremap <S-Tab> <C-w>W
nnoremap <silent> j gj
nnoremap <silent> gj j
nnoremap <silent> k gk
nnoremap <silent> gk k
"nnoremap <silent> <C-n> :bn<CR>
"nnoremap <silent> <C-p> :bp<CR>
nnoremap <silent> <Leader>d :bd<CR>
nnoremap <silent> <Leader>dd :bd!<CR>
" }}}
" Auto Commands {{{
augroup MyVimrc
  autocmd!
  autocmd FileType vim call s:setting_for_vim()
augroup END

function! s:setting_for_vim()
  nnoremap <buffer> <Leader>r :so%<CR>
endfunction
" }}}
" Packages {{{
" vim-packager
command! PackagerInstall call PackagerInit() | call packager#install()
command! -bang PackagerUpdate call PackagerInit() | call packager#update({ 'force_hooks': '<bang>' })
command! PackagerClean call PackagerInit() | call packager#clean()
command! PackagerStatus call PackagerInit() | call packager#status()
" lightline.vim
let g:lightline = {'colorscheme': 'wombat'}
" vim-dirvish
let g:loaded_netrwPlugin = 1
command! -nargs=? -complete=dir Explore Dirvish <args>
command! -nargs=? -complete=dir Sexplore belowright split | silent Dirvish <args>
command! -nargs=? -complete=dir Vexplore leftabove vsplit | silent Dirvish <args>
" }}}
" vim:foldmethod=marker
